excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://leoCamilo.github.io
name: gitBlogLeo
description: this site was done for the POO II course and has all content created by me.
author: leoCamilo
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 